# Generated by Django 4.1.2 on 2022-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Title'),
        ),
    ]
